name: podepmgr
description: dart version of the podepmgr manager
version: 0.1.0

environment:
  sdk: ^3.4.3

dependencies:
  args: ^2.6.0
  build_runner: ^2.4.11
  dart_console: ^4.1.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
